name: mudblazor-ci

on:
  push:
    branches: [ feature/github-actions ]
    
  pull_request:
    branches: [ feature/github-actions ]

env:
  AZURE_WEBAPP_NAME: mudblazor-dev
  AZURE_WEBAPP_PACKAGE_PATH: './src/MudBlazor.Docs.Server'
  DOTNET_VERSION: '5.0.x'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore
      run: dotnet restore ./src/MudBlazor.sln

    - name: Build
      run: dotnet build ./src/MudBlazor.sln -c release

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Test
      run: dotnet test ./src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj -c release --blame-hang --blame-hang-timeout 60s /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAttribute='ExcludeFromCodeCoverage' /p:Include='[MudBlazor]*' /p:SkipAutoProps=true /p:CoverletOutput='./TestResults/'
      
    - name: Test Coverage
      uses: codacy/codacy-coverage-reporter-action@v1.1.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./src/MudBlazor.UnitTests/TestResults/coverage.cobertura.xml

  deploy:
    name: Deploy
    needs: [build, test]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Publish
      run: dotnet publish ./src/MudBlazor.Docs.Server -c release -o ./src/MudBlazor.Docs.Server/mudblazor-dev
      
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with: 
          app-name: mudblazor-dev
          publish-profile: ${{ secrets.PUBLISH_MUDBLAZOR_DEV  }}
          package: ./src/MudBlazor.Docs.Server/mudblazor-dev
          
