name: mudblazor-ci

on:
  push:
    branches: [ feature/github-actions ]
    
  pull_request:
    branches: [ feature/github-actions ]

env:
  AZURE_WEBAPP_NAME: mudblazor-test
  AZURE_WEBAPP_PACKAGE_PATH: MudBlazor.Docs.Server/publish
  DOTNET_VERSION: '5.0.x'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
        run:
          working-directory: ./src
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Setup dotnet 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
        
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --blame-hang --blame-hang-timeout 60s /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAttribute='ExcludeFromCodeCoverage' /p:Include='[MudBlazor]*' /p:SkipAutoProps=true /p:CoverletOutput='./TestResults/'
        
      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.cobertura.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
        
    
  
          
